"""
Django settings for espacio project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from django.contrib.messages import constants as messages
from celery.schedules import crontab
import dj_database_url #Deploy en render


BASE_DIR = Path(__file__).resolve().parent.parent  

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "inseguro-default-dev-key") #Deploy en render

DEBUG = os.getenv('DEBUG', 'False') == 'True' #Deploy en render

ALLOWED_HOSTS = ['proyecto-espacio.onrender.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',  
    'crispy_forms',
    'django_bootstrap5',
    'crispy_bootstrap5',

    # APLICACIONES PERSONALIZADAS:
    # ¡IMPORTANTE! Aquí van SIN el prefijo 'espacio.'
    # porque 'espacio/' ya es la raíz que se añade al PYTHONPATH,
    # y tus apps están directamente dentro de esa raíz.
    'myproject.webPublic',  
    'myproject.management', 
    'myproject.empleados',  
    'myproject.eventos',    
    'myproject.planes',     
    'myproject.clientes',   
    'myproject.configuracion',
    'myproject.calendario', 

    'cloudinary_storage',  
    'django.contrib.staticfiles',
    'cloudinary',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'myproject.core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR.parent, 'espacio', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.core.wsgi.application' 

DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL')) #Deploy en render
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'es-eu'

USE_TZ = True

TIME_ZONE = 'America/Argentina/Buenos_Aires'  # Ajusta según tu zona horaria

USE_I18N = True
 
STATIC_URL = '/static/' #Deploy en render
STATICFILES_DIRS = [os.path.join(BASE_DIR, '../static')] #Deploy en render
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #Deploy en render
STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticCloudinaryStorage'  #Deploy en render

#MEDIA_URL = '/media/' #Deploy en render utilizamos cloudinary
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media') #Deploy en render  cloudinary

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage' #Deploy en render
CLOUDINARY_STORAGE = { #Deploy en render
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'), #Deploy en render
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'), #Deploy en render
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'), #Deploy en render
}

SECURE_SSL_REDIRECT = True #Deploy en render
SESSION_COOKIE_SECURE = True #Deploy en render
CSRF_COOKIE_SECURE = True #Deploy en render

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5" 
CRISPY_TEMPLATE_PACK = "bootstrap5"

APPEND_SLASH = True

MESSAGE_TAGS = {
    messages.ERROR: 'danger', 
    messages.SUCCESS: 'success',
    messages.INFO: 'info',
    messages.WARNING: 'warning',
}


CSRF_TRUSTED_ORIGINS = [
    'https://proyecto-espacio.onrender.com', #Deploy en render
    'https://localhost:8000',
    'http://localhost:8000',
]

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
