# Generated by Django 5.1.7 on 2025-05-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionevento',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
