# Generated by Django 5.1.7 on 2025-05-23 02:03

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudio', models.CharField(default='Estudio', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('cuit', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('maps', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('texto_hero', models.TextField(blank=True)),
                ('mensaje_whatsapp_plan', models.CharField(blank=True, max_length=255)),
                ('mensaje_whatsapp_evento', models.CharField(blank=True, max_length=255)),
                ('dias_habilitados', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=52)),
                ('horario_semana_inicio', models.TimeField(blank=True, null=True)),
                ('horario_semana_fin', models.TimeField(blank=True, null=True)),
                ('horario_sabado_inicio', models.TimeField(blank=True, null=True)),
                ('horario_sabado_fin', models.TimeField(blank=True, null=True)),
                ('horario_domingo_inicio', models.TimeField(blank=True, null=True)),
                ('horario_domingo_fin', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
