# Generated by Django 5.1.7 on 2025-05-23 02:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField(unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('dias', models.CharField(blank=True, max_length=100, null=True)),
                ('hora', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('regular', 'Regular'), ('eventual', 'Eventual')], default='regular', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(default=datetime.date.today)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('ultima_confirmacion', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planes.plan')),
            ],
        ),
    ]
