# Generated by Django 5.1.7 on 2025-05-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='empleados/')),
                ('mostrar_en_web', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
